specfile_path: abrt-java-connector.spec
files_to_sync:
  - .packit.yml
  - abrt-java-connector.spec
upstream_package_name: abrt-java-connector
upstream_project_url: https://github.com/abrt/abrt-java-connector
downstream_package_name: abrt-java-connector
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branch: fedora-all
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
